---
- hosts: apps
  become: yes

  tasks:
    - name: "download 'api' file"
      get_url:
        url: https://github.com/jusan-singularity/track-devops-systemd-api/releases/download/v0.1/api
        dest: /tmp/api
        mode: '0755'
    - name: "mount 'api.service' file for 'api'"
      copy:
        src: api.service
        dest: /etc/systemd/system/api.service
    - name: "run service"
      service:
        name: api
        state: started
        enabled: yes

- hosts: lb
  become: yes

  tasks:
    - name: "install-nginx"
      apt: name=nginx state=present

    - name: "mounting 'nginx.conf' to server"
      copy:
        src: "./nginx.conf"
        dest: "/etc/nginx/nginx.conf"
      notify: "reload-nginx"

    - name: "removing 'default.conf' from server"
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: "mounting 'serv.conf.j2'"
      template:
        src: "./server.conf.j2"
        dest: "/etc/nginx/conf.d/{{ item.server_name }}.conf"
      vars:
        server_port: "{{ item.server_port }}"
        server_name: "{{ item.server_name }}"
        locations: "{{ item.locations }}"
      loop:
        - server_port: 7070
          server_name: jmart-ansible.kz
          locations:
            - path: /main
              status_code: 200
              message: Добро пожаловать на JMart!
            - path: /profile
              status_code: 201
              message: Это страница профиля.

        - server_port: 8080
          server_name: jusan-ansible.kz
          locations:
            - path: /
              status_code: 200
              message: Добро пожаловать на Jusan Bank!
            - path: /account
              status_code: 202
              message: Здесь ваш банковский счет!

        - server_port: 9090
          server_name: invest-ansible.kz
          locations:
            - path: /home
              status_code: 200
              message: Добро пожаловать на Jusan Invest!
            - path: /user
              status_code: 203
              message: Это страница с вашим брокерским счетом.

    - name: "mounting 'serv.conf.j2'"
      template:
        src: "app.conf.j2"
        dest: "/etc/nginx/conf.d/{{ server_name }}.conf"
      vars:
        server_port: 80
        server_name: jusan-apps.kz
        apps:
        - service_name: local-vps-23
          port: 9090
        - service_name: local-vps-24
          port: 9090
      notify: "reload-nginx"

  handlers:
    - name: "reload-nginx"
      service: name=nginx state=reloaded